### ISSUE TITLE
Flutter Build failed after adding this package 

### ISSUE THREAD

**Issue by ermiasamb** [Mamasodikov/cosmos_epub#2]
**Platform info**
Operating System     Windows 10
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor

Dart SDK version: 3.4.0 (stable) (Mon May 6 07:59:58 2024 -0700) on "windows_x64"
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources

**Error message:**

`Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Checking the license for package Android SDK Platform 30 in C:\Users\User\AppData\Local\Android\Sdk\licenses
License for package Android SDK Platform 30 accepted.
Preparing "Install Android SDK Platform 30 (revision: 3)".
"Install Android SDK Platform 30 (revision: 3)" ready.
Installing Android SDK Platform 30 in C:\Users\User\AppData\Local\Android\Sdk\platforms\android-30
"Install Android SDK Platform 30 (revision: 3)" complete.
"Install Android SDK Platform 30 (revision: 3)" finished.
../../AppData/Local/Pub/Cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
 - 'PageController' is from 'package:flutter/src/widgets/page_view.dart' ('/D:/lib/flutter/packages/flutter/lib/src/widgets/page_view.dart').
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('/D:/lib/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
      scrollController: child.controller,
                              ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\lib\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21m 16s
Error: Gradle task assembleDebug failed with exit code 1`

**Comment by Mamasodikov** [comment]
Thanks for opening the issue. I'll try to look into it ASAP.

**Comment by Mamasodikov** [comment]
#4
