### ISSUE TITLE
After adding the package it gives this error

### ISSUE THREAD

**Issue by ZainRaza78** [Mamasodikov/cosmos_epub#3]
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
../../AppData/Local/Pub/Cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
 - 'PageController' is from 'package:flutter/src/widgets/page_view.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_view.dart').
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
      scrollController: child.controller,
                              ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 38s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by Mamasodikov** [comment]
https://github.com/Mamasodikov/cosmos_epub/issues/2#issue-2341722801
